import React, { useEffect, useState } from 'react';
import { fetchAllVideos } from '../../adapter/videos';
import '../../styles/Videos.scss';
import Video from '../Video';

function Videos() {
  const [videos, setVideos] = useState([
    {
      created_at: '2018-07-09T22:49:13.237Z',
      updated_at: '2021-12-01T20:00:41.262Z',
      title: 'Stones by the waterfall',
      base_filename: 'Agua-natural',
      poster: 'https://storage.coverr.co/p/rhOM3iuhDqxedD7lKLpPO34yN2lhf5Kk',
      thumbnail: 'https://storage.coverr.co/t/rhOM3iuhDqxedD7lKLpPO34yN2lhf5Kk',
      description:
        'Close-up shot of some grey stones, with a beautiful waterfall in the background. ',
      state: 'published',
      is_vertical: false,
      tags: [
        'stones',
        'rocks',
        'iceland',
        'waterfall',
        'forest',
        'woods',
        'greenery',
        'mountains',
        'pebbles',
        'water',
        'lake',
        'pond',
        'nature',
        'beautiful',
        'cinematic',
        'background',
        'loop',
        'cloudy weather',
        'peaceful',
        'setting',
        'zoom background',
        'zoom virtual background',
        'virtual background',
      ],
      downloads: 65740,
      views: 895608,
      likes: 0,
      contributor_id: 0,
      published_at: '2016-04-25T00:00:00.000Z',
      playback_id: 'rhOM3iuhDqxedD7lKLpPO34yN2lhf5Kk',
      aspect_ratio: '16:9',
      duration: 13.04,
      max_height: 1080,
      max_width: 1920,
      video_id: 'ee0b4132-65ba-4813-a2d7-1f7c2853dd81',
      d2v_ratio: 0.44025895,
      id: 'hWGAKF358u',
      published_at_timestamp: 1461542400000,
      objectID: 'hWGAKF358u',
    },
    {
      created_at: '2018-07-09T22:49:17.114Z',
      updated_at: '2021-12-01T20:00:42.733Z',
      title: 'Curtain blowing in the wind',
      base_filename: 'Billowing',
      poster: 'https://storage.coverr.co/p/ba21g02uIih01OZfcJBEaRoee9Pr231LnK',
      thumbnail:
        'https://storage.coverr.co/t/ba21g02uIih01OZfcJBEaRoee9Pr231LnK',
      description:
        'A cinematic shot of a curtain blowing in the wind, with a spacious backyard in the background. ',
      state: 'published',
      is_vertical: false,
      tags: [
        'billowing',
        'curtain',
        'backyard',
        'open',
        'windows',
        'blue',
        'green',
        'plants',
        'artsy',
        'background',
        'loop',
        'outside',
        'outdoors',
        'indoors',
        'daylight',
        'sunny',
        'bricks',
        'spacious',
        'relaxing',
        'peaceful',
        'beautiful',
        'environment',
        'scenery',
        'zoom background',
        'zoom virtual background',
        'virtual background',
      ],
      downloads: 60105,
      views: 166462,
      likes: 0,
      contributor_id: 0,
      published_at: '2016-04-25T00:00:00.000Z',
      playback_id: 'ba21g02uIih01OZfcJBEaRoee9Pr231LnK',
      aspect_ratio: '16:9',
      duration: 12.7,
      max_height: 1080,
      max_width: 1920,
      video_id: 'eb3eece9-558a-438f-a2f8-343b3880616f',
      d2v_ratio: 0.45739958,
      id: 'uQVt3hxBIO',
      published_at_timestamp: 1461542400000,
      objectID: 'uQVt3hxBIO',
    },
    {
      created_at: '2018-07-09T22:48:14.017Z',
      updated_at: '2021-12-01T20:00:38.580Z',
      title: 'A view of a river',
      base_filename: 'Down_by_the_River',
      poster: 'https://storage.coverr.co/p/5D8KLE02E7ghzttOvoRNkPYpNvFctoWK5',
      thumbnail:
        'https://storage.coverr.co/t/5D8KLE02E7ghzttOvoRNkPYpNvFctoWK5',
      description:
        'In this shot, we can see a beautiful river surrounded by lots of trees and plants.',
      state: 'published',
      is_vertical: false,
      tags: [
        'river',
        'trees ',
        'forest',
        'plants',
        'autumn',
        'leaves',
        'nature',
        'background',
        'loop',
        'beautiful',
        'scenery',
        'reflection',
        'daylight',
        'calming',
        'oasis',
        'peaceful',
        'green',
        'yellow',
        'orange',
        'fall',
        'bushes',
        'grass',
      ],
      downloads: 47781,
      views: 151279,
      likes: 0,
      contributor_id: 0,
      published_at: '2017-11-13T00:00:00.000Z',
      playback_id: '5D8KLE02E7ghzttOvoRNkPYpNvFctoWK5',
      aspect_ratio: '16:9',
      duration: 11.8,
      max_height: 1080,
      max_width: 1920,
      video_id: '8fe5ecf7-3013-4541-9002-fb2fe15b983b',
      d2v_ratio: 0.43165535,
      id: 'BxLxwvKDDY',
      published_at_timestamp: 1510531200000,
      objectID: 'BxLxwvKDDY',
    },
    {
      created_at: '2020-03-27T14:57:30.394Z',
      updated_at: '2021-12-01T20:00:43.531Z',
      title: 'Mountains in the fog',
      base_filename: 'coverr-aerial-view-of-rocky-mountains-1585320758193',
      poster: 'https://storage.coverr.co/p/TEerln00m5BX5hsDYavm12mzBSO3YPlKR',
      thumbnail:
        'https://storage.coverr.co/t/TEerln00m5BX5hsDYavm12mzBSO3YPlKR',
      description: 'Aerial shot of rocky mountains on a foggy day.',
      state: 'published',
      is_vertical: false,
      tags: [
        'mountains',
        'rocks',
        'rocky',
        'drone',
        'drone view',
        'aerial',
        'green',
        'greenery',
        'plants',
        'grass',
        'trees',
        'pine',
        'sky',
        'clouds',
        'river',
        'river flow',
        'wood',
        'forest',
        'landscape',
        'outdoor',
        'outside',
        'open-air',
        'beautiful',
        'peaceful',
        'scenery',
        'grass field',
        'foggy weather',
        'foggy',
        'cloudy day',
        'cloudy weather',
        'calm water',
        'reflection',
        'nature',
        'background',
      ],
      downloads: 45826,
      views: 1263846,
      likes: 0,
      contributor_id: 0,
      published_at: '2020-03-27T15:47:06.223Z',
      playback_id: 'TEerln00m5BX5hsDYavm12mzBSO3YPlKR',
      aspect_ratio: '16:9',
      duration: 22.6903,
      max_height: 1080,
      max_width: 1920,
      video_id: 'a55a4d7c-7084-48e9-93af-77d15b1af7aa',
      d2v_ratio: 0.40861553,
      id: '27KwMoV3Hn',
      published_at_timestamp: 1585324026223,
      objectID: '27KwMoV3Hn',
    },
    {
      created_at: '2019-10-27T10:45:51.088Z',
      updated_at: '2021-12-01T20:00:39.793Z',
      title: 'Rocks by the lake ',
      base_filename: 'coverr-mountain-lake-1572171891276',
      poster: 'https://storage.coverr.co/p/DUKhFlmGwTyN2vdUe02klp00e54aqapqTE',
      thumbnail:
        'https://storage.coverr.co/t/DUKhFlmGwTyN2vdUe02klp00e54aqapqTE',
      description: 'Breathtaking shot of rocks and mountains by the lake. ',
      state: 'published',
      is_vertical: false,
      tags: [
        'lake',
        'mountain',
        'coast',
        'coastline',
        'view',
        'landscape',
        'outside',
        'outdoor',
        'open-air',
        'hill',
        'wood',
        'forest',
        'pine',
        'rest',
        'relaxation',
        'trees',
        'rocks',
        'green',
        'nature',
        'greenery',
        'breathtaking',
        'beautiful',
        'colorful',
        'vibrant',
        'stones',
        'pebbles',
        'clear water',
        'calm water',
        'peaceful',
        'scenery',
        'bushes',
        'shrub',
        'quiet',
        'tranquility',
        'background',
        'loop',
        'still shot',
        'paradise',
        'travel',
        'sightseeing',
        'zoom background',
        'zoom virtual background',
        'virtual background',
      ],
      downloads: 45040,
      views: 151940,
      likes: 0,
      contributor_id: 0,
      published_at: '2019-10-31T05:53:33.825Z',
      playback_id: 'DUKhFlmGwTyN2vdUe02klp00e54aqapqTE',
      aspect_ratio: '16:9',
      duration: 10.026667,
      max_height: 1080,
      max_width: 1920,
      video_id: 'dc6dc834-469e-479a-9c66-5801d8d07d8d',
      d2v_ratio: 0.40937337,
      id: 'SzbwQXG2Vc',
      published_at_timestamp: 1572501213825,
      objectID: 'SzbwQXG2Vc',
    },
    {
      created_at: '2018-07-09T22:48:41.271Z',
      updated_at: '2021-12-01T20:00:42.735Z',
      title: 'Worker on Tulum Beach',
      base_filename: 'Tulum',
      poster: 'https://storage.coverr.co/p/bhnNW022Hykx6POeLwxpg02hzB9VY02xW98',
      thumbnail:
        'https://storage.coverr.co/t/bhnNW022Hykx6POeLwxpg02hzB9VY02xW98',
      description:
        'Still shot of Tulum beach with a worker putting soil into a wheelbarrow, in the background.',
      state: 'published',
      is_vertical: false,
      tags: [
        'tulum',
        'beach',
        'beautiful',
        'scenery',
        'water',
        'oceanic',
        'paradise',
        'sand',
        'clear sky',
        'sunny weather',
        'summer',
        'holiday',
        'vacation',
        'worker',
        'table',
        'cafe',
        'beer',
        'relaxing',
        'chilling',
        'plants',
        'greenery',
        'trees',
        'rocks',
        'background',
        'zoom background',
        'zoom virtual background',
        'virtual background',
        'soil',
        'wheel barrow',
        'wheelbarrow',
        'shovel',
        'tulum beach',
      ],
      downloads: 40990,
      views: 152785,
      likes: 0,
      contributor_id: 0,
      published_at: '2016-12-12T00:00:00.000Z',
      playback_id: 'bhnNW022Hykx6POeLwxpg02hzB9VY02xW98',
      aspect_ratio: '16:9',
      duration: 11.48,
      max_height: 1080,
      max_width: 1920,
      video_id: 'e7696963-b849-4e61-955f-ee98b11a393e',
      d2v_ratio: 0.40727928,
      id: 'Q635G0vUB3',
      published_at_timestamp: 1481500800000,
      objectID: 'Q635G0vUB3',
    },
    {
      created_at: '2020-01-09T20:04:48.014Z',
      updated_at: '2021-12-01T20:00:43.531Z',
      title: 'Sunrise in Costa Rica ',
      base_filename: 'coverr-dawn-in-costa-rica--1578599828484',
      poster: 'https://storage.coverr.co/p/yxhlPGs02KhqKs3Hr5nWKs8Vbd5GUpLhQ',
      thumbnail:
        'https://storage.coverr.co/t/yxhlPGs02KhqKs3Hr5nWKs8Vbd5GUpLhQ',
      description: 'Cinematic shot of the sun rising in Costa Rica.',
      state: 'published',
      is_vertical: false,
      tags: [
        'dawn',
        'sea',
        'water',
        'waves',
        'sun',
        'sunrise',
        'sky',
        'clouds',
        'yellow',
        'trees',
        'hills',
        'yacht',
        'ship',
        'coast',
        'coastline',
        'costa rica',
        'landscape',
        'view',
        'outdoor',
        'outside',
        'open-air',
        'zoom background',
        'zoom virtual background',
        'virtual background',
        'cinematic',
        'vibrant',
        'colors',
        'beautiful',
        'peaceful',
        'scenery',
        'calm water',
        'mesmerizing',
        'wonderful',
        'sunset hours',
        'orange',
        'cloudscape',
        'cloudy weather',
        'cloudy day',
        'island',
        'travel',
        'holiday',
        'vacation',
        'background',
        'loop',
      ],
      downloads: 40238,
      views: 206460,
      likes: 0,
      contributor_id: 0,
      published_at: '2020-01-14T07:36:28.829Z',
      playback_id: 'yxhlPGs02KhqKs3Hr5nWKs8Vbd5GUpLhQ',
      aspect_ratio: '16:9',
      duration: 11.378044,
      max_height: 1080,
      max_width: 1920,
      video_id: '4074a2bb-2ffc-4b19-b989-69589207d5bc',
      d2v_ratio: 0.40580252,
      id: 'HM7pVL1BAT',
      published_at_timestamp: 1578987388829,
      objectID: 'HM7pVL1BAT',
    },
    {
      created_at: '2018-07-09T22:49:06.673Z',
      updated_at: '2021-12-01T20:00:43.531Z',
      title: 'Soaring through the clouds ',
      base_filename: 'In-The-Clouds',
      poster: 'https://storage.coverr.co/p/aV8I8U6jeT5ucRCMPLKHnEbfrb4sDEYe',
      thumbnail: 'https://storage.coverr.co/t/aV8I8U6jeT5ucRCMPLKHnEbfrb4sDEYe',
      description:
        'POV shot of soaring through the clouds, from inside an airplane.',
      state: 'published',
      is_vertical: false,
      tags: [
        'flying',
        'airplane',
        'flight',
        'plane',
        'pov',
        'passenger',
        'window ',
        'seat',
        'clear sky',
        'clouds',
        'cotton candy',
        'blue',
        'peaceful',
        'beautiful',
        'setting',
        'travel',
        'holiday',
        'vacation',
        'aircraft',
        'up',
        'sky',
        'background',
        'loop',
        'zoom background',
        'zoom virtual background',
        'virtual background',
        'soaring',
      ],
      downloads: 32833,
      views: 235383,
      likes: 0,
      contributor_id: 0,
      published_at: '2016-04-25T00:00:00.000Z',
      playback_id: 'aV8I8U6jeT5ucRCMPLKHnEbfrb4sDEYe',
      aspect_ratio: '16:9',
      duration: 8.667,
      max_height: 1080,
      max_width: 1920,
      video_id: '0cc0547a-8901-4c66-bbd8-fdc191394800',
      d2v_ratio: 0.45665005,
      id: 'h2DAoXGSBh',
      published_at_timestamp: 1461542400000,
      objectID: 'h2DAoXGSBh',
    },
    {
      title: 'A guy takes photos of a seascape',
      description:
        'Medium shot of a guy taking photos of a seascape with his digital camera.',
      tags: [
        'photographs',
        'sea',
        'rocks',
        'take a photo',
        'make photo',
        'photographing',
        'photo',
        'pictures',
        'digital',
        'camera',
        'foreshortening',
        'ocean',
        'seascape',
        'landscape',
        'travel',
        'traveler',
        'wanderlust',
        'praia da ursa',
        'ursa beach',
        'portugal',
        'guy',
        'curly',
        'man',
        'environment',
        'cliff',
        'edge',
        'precipice',
        'windy',
        'people',
        'nature',
      ],
      downloads: 32382,
      is_vertical: false,
      created_at: '2021-09-07T17:35:12.480Z',
      updated_at: '2021-12-01T20:00:39.793Z',
      base_filename: 'coverr--06-21-friends-at-praia-da-ursa-winter_0057-0401',
      poster:
        'https://storage.coverr.co/p/MwLuuLTiEvc00FFR1ifarb02Ia01S00u01z1U',
      thumbnail:
        'https://storage.coverr.co/t/MwLuuLTiEvc00FFR1ifarb02Ia01S00u01z1U',
      state: 'published',
      views: 6750,
      likes: 0,
      contributor_id: 0,
      published_at: '2021-10-17T12:56:39.207Z',
      playback_id: 'MwLuuLTiEvc00FFR1ifarb02Ia01S00u01z1U',
      aspect_ratio: '16:9',
      duration: 18.583333,
      max_height: 1152,
      max_width: 2048,
      video_id: 'ce7e23c3-6b36-4167-88c9-1a1768f7fd15',
      id: 'MHeTZWMlCC',
      published_at_timestamp: 1634475399207,
      d2v_ratio: 0,
      objectID: 'MHeTZWMlCC',
    },
    {
      title: 'Friends exploring a rocky beach ',
      description:
        'Long shot of friends exploring a stony beach near a rocky cliff in the evening.\n',
      tags: [
        'seashore',
        'beach',
        'sea',
        'friends',
        'walking',
        'exploring',
        'contemplate',
        'seaside',
        'coast',
        'coastline',
        'rocky',
        'stony',
        'cloudy weather',
        'gloomy',
        'evening',
        'nature',
        'people',
        'landscape',
        'outside',
        'outdoors',
        'open-air',
        'fresh air',
      ],
      downloads: 31306,
      is_vertical: false,
      created_at: '2021-11-15T11:02:39.695Z',
      updated_at: '2021-12-02T20:48:59.565Z',
      base_filename: 'coverr--08-21-girl-on-rainy-day-at-the-beach_03-1109',
      poster: 'https://storage.coverr.co/p/S5WiiB5X2AutnNUrd00blLlyLALM2kjF8',
      thumbnail:
        'https://storage.coverr.co/t/S5WiiB5X2AutnNUrd00blLlyLALM2kjF8',
      state: 'published',
      views: 6066,
      likes: 0,
      contributor_id: 0,
      published_at: '2021-11-25T11:04:23.588Z',
      playback_id: 'S5WiiB5X2AutnNUrd00blLlyLALM2kjF8',
      aspect_ratio: '16:9',
      duration: 12.303967,
      max_height: 1152,
      max_width: 2048,
      video_id: '92bde1fc-fd44-4b55-8284-382f44f6824c',
      id: 'St0sG7y8HW',
      published_at_timestamp: 1637838263588,
      d2v_ratio: 0,
      objectID: 'St0sG7y8HW',
    },
    {
      title: 'A man taking photos of a river quay',
      description:
        'Medium shot of a man taking photos of a river quay at night.\n',
      tags: [
        'river',
        'night',
        'photos',
        'quay',
        'bridge',
        'city',
        'smartphone',
        'take a photo',
        'make photo',
        'photographing',
        'night life',
        'night light',
        'city life',
        'street light',
        'bokeh',
        'shore',
        'man',
        'guy',
        'landscape',
        'evening',
        'people',
        'urban',
        'lifestyle',
      ],
      downloads: 31035,
      is_vertical: false,
      created_at: '2021-10-25T13:06:33.128Z',
      updated_at: '2021-12-01T20:00:43.531Z',
      base_filename: 'coverr--08-21-asian-man-night-street_06-5856',
      poster: 'https://storage.coverr.co/p/iv8W8g6T0058dIeOGyI87dV01sTFN4wvjf',
      thumbnail:
        'https://storage.coverr.co/t/iv8W8g6T0058dIeOGyI87dV01sTFN4wvjf',
      state: 'published',
      views: 2183,
      likes: 0,
      contributor_id: 0,
      published_at: '2021-11-10T06:44:04.178Z',
      playback_id: 'iv8W8g6T0058dIeOGyI87dV01sTFN4wvjf',
      aspect_ratio: '16:9',
      duration: 13.179833,
      max_height: 1152,
      max_width: 2048,
      video_id: 'b947505a-d4d1-497f-bc04-7588ada5bffb',
      id: 'nms4H0L9oP',
      published_at_timestamp: 1636526644178,
      d2v_ratio: 0,
      objectID: 'nms4H0L9oP',
    },
    {
      created_at: '2020-01-09T15:57:02.612Z',
      updated_at: '2021-12-01T20:00:42.733Z',
      title: 'Bird walking on the beach',
      base_filename: 'coverr-bird-walking-on-the-beach-1578584793241',
      poster: 'https://storage.coverr.co/p/ZbtbfyqRyAMzBVE67qR5Gjl6uJwQBKZb',
      thumbnail: 'https://storage.coverr.co/t/ZbtbfyqRyAMzBVE67qR5Gjl6uJwQBKZb',
      description: 'Still shot of a bird walking on an empty beach.',
      state: 'published',
      is_vertical: false,
      tags: [
        'beach',
        'bird',
        'walk',
        'walking',
        'sea',
        'water',
        'sand',
        'hills',
        'flowers',
        'greenery',
        'sky',
        'clouds',
        'coast',
        'coastline',
        'wave',
        'costa rica',
        'landscape',
        'view',
        'outdoor',
        'outside',
        'open-air',
        'zoom background',
        'zoom virtual background',
        'virtual background',
        'crashing waves',
        'islands',
        'island',
        'flower garden',
        'blossom',
        'bloom',
        'flora',
        'floral',
        'silence',
        'quiet',
        'beautiful',
        'peaceful',
        'scenery',
        'clear sky',
        'cloudscape',
        'alone',
        'nature',
        'background',
      ],
      downloads: 30419,
      views: 118832,
      likes: 0,
      contributor_id: 0,
      published_at: '2020-01-14T07:35:47.839Z',
      playback_id: 'ZbtbfyqRyAMzBVE67qR5Gjl6uJwQBKZb',
      aspect_ratio: '16:9',
      duration: 9.783333,
      max_height: 1080,
      max_width: 1920,
      video_id: '9f9d9495-1534-4fa6-9ecb-97a9f32cf5d3',
      d2v_ratio: 0.39631176,
      id: 'xYngxQJw5E',
      published_at_timestamp: 1578987347839,
      objectID: 'xYngxQJw5E',
    },
    {
      title: 'Friends taking photos on the edge of a cliff',
      description: 'Long shot of friends taking photos on the edge of a cliff.',
      tags: [
        'photographs',
        'sea',
        'friends',
        'rocks',
        'take a photo',
        'make photo',
        'photographing',
        'photo',
        'pictures',
        'digital',
        'camera',
        'guy',
        'foreshortening',
        'seascape',
        'cliff',
        'precipice',
        'edge',
        'horizon',
        'landscape',
        'ocean',
        'travel',
        'traveler',
        'wanderlust',
        'praia da ursa',
        'ursa beach',
        'portugal',
        'windy',
        'environment',
        'natural',
        'beauty',
        'people',
        'nature',
      ],
      downloads: 30010,
      is_vertical: false,
      created_at: '2021-09-07T17:22:30.062Z',
      updated_at: '2021-12-01T20:00:39.793Z',
      base_filename: 'coverr--06-21-friends-at-praia-da-ursa-winter_0055-9552',
      poster: 'https://storage.coverr.co/p/BKu4zXol4LJAPadcVc4AqRJIKRhMAVUf',
      thumbnail: 'https://storage.coverr.co/t/BKu4zXol4LJAPadcVc4AqRJIKRhMAVUf',
      state: 'published',
      views: 3321,
      likes: 0,
      contributor_id: 0,
      published_at: '2021-10-17T12:56:32.656Z',
      playback_id: 'BKu4zXol4LJAPadcVc4AqRJIKRhMAVUf',
      aspect_ratio: '16:9',
      duration: 27.125,
      max_height: 1152,
      max_width: 2048,
      video_id: '2e21cce0-dd94-4542-b720-645ce9738833',
      id: 'JJC0m77HJN',
      published_at_timestamp: 1634475392656,
      d2v_ratio: 0,
      objectID: 'JJC0m77HJN',
    },
    {
      title: 'Friends walking along a seashore',
      description:
        'Aerial shot of friends walking on a stony beach in the evening.\n',
      tags: [
        'sea',
        'walking',
        'beach',
        'seashore',
        'seaside',
        'coast',
        'coastline',
        'rocky',
        'stony',
        'friends',
        'ocean',
        'water',
        'horizon',
        'blue sky',
        'cloudy weather',
        'gloomy',
        'evening',
        'landscape',
        'nature',
        'people',
        'outdoors',
        'outside',
        'open-air',
        'fresh air',
      ],
      downloads: 29982,
      is_vertical: false,
      created_at: '2021-11-15T11:00:36.948Z',
      updated_at: '2021-12-30T20:08:06.072Z',
      base_filename: 'coverr--08-21-girl-on-rainy-day-at-the-beach_02-9680',
      poster: 'https://storage.coverr.co/p/D1ydMVukj1HebD9Ok019F9lrBp8B01zvN7',
      thumbnail:
        'https://storage.coverr.co/t/D1ydMVukj1HebD9Ok019F9lrBp8B01zvN7',
      state: 'published',
      views: 4538,
      likes: 0,
      contributor_id: 0,
      published_at: '2021-11-25T11:04:21.052Z',
      playback_id: 'D1ydMVukj1HebD9Ok019F9lrBp8B01zvN7',
      aspect_ratio: '16:9',
      duration: 17.809467,
      max_height: 1152,
      max_width: 2048,
      video_id: '10ff537f-a3fd-4bea-aab5-987a6837e73d',
      id: 'KaCV6dl3Tt',
      published_at_timestamp: 1637838261052,
      d2v_ratio: 0,
      objectID: 'KaCV6dl3Tt',
    },
    {
      title: 'A young girl walking along a seashore',
      description:
        'Side view, close-up shot of a girl walking along the coast in cloudy weather.\n',
      tags: [
        'sea',
        'coast',
        'walking',
        'girl',
        'seashore',
        'seaside',
        'coastline',
        'beach',
        'ocean',
        'cloudy',
        'gloomy',
        'weather',
        'horizon',
        'landscape',
        'contemplate',
        'nature',
        'people',
        'outside',
        'outdoors',
        'open-air',
        'fresh air',
      ],
      downloads: 29447,
      is_vertical: false,
      created_at: '2021-11-15T10:58:15.132Z',
      updated_at: '2021-12-02T20:43:28.179Z',
      base_filename: 'coverr--08-21-girl-on-rainy-day-at-the-beach_01-5850',
      poster: 'https://storage.coverr.co/p/ngZWMT4LoOgX8fecHhD02WPsAxJ9DCMsD',
      thumbnail:
        'https://storage.coverr.co/t/ngZWMT4LoOgX8fecHhD02WPsAxJ9DCMsD',
      state: 'published',
      views: 3743,
      likes: 0,
      contributor_id: 0,
      published_at: '2021-11-25T11:04:19.351Z',
      playback_id: 'ngZWMT4LoOgX8fecHhD02WPsAxJ9DCMsD',
      aspect_ratio: '16:9',
      duration: 19.4778,
      max_height: 1152,
      max_width: 2048,
      video_id: '76820ce1-3618-4790-a63d-d72ef4f5568c',
      id: 'LE6YNZXUyi',
      published_at_timestamp: 1637838259351,
      d2v_ratio: 0,
      objectID: 'LE6YNZXUyi',
    },
    {
      title: 'Asian man using his a smartphone as a mirror',
      description:
        'Medium close-up shot of an Asian man using his smartphone as a mirror.\n',
      tags: [
        'hairstyle',
        'street',
        'night',
        'city',
        'smartphone',
        'mirror',
        'front camera',
        'car',
        'adjust',
        'hair',
        'man',
        'guy',
        'bokeh',
        'street light',
        'city life',
        'night life',
        'night light',
        'parking',
        'asian',
        'urban',
        'people',
        'lifestyle',
      ],
      downloads: 27940,
      is_vertical: false,
      created_at: '2021-10-26T09:13:45.907Z',
      updated_at: '2021-12-01T20:00:43.531Z',
      base_filename: 'coverr--08-21-asian-man-night-street_18-1533',
      poster: 'https://storage.coverr.co/p/ppCBXN7CGvl5S01SpnvDDgfBRJMhRYwZ1',
      thumbnail:
        'https://storage.coverr.co/t/ppCBXN7CGvl5S01SpnvDDgfBRJMhRYwZ1',
      state: 'published',
      views: 3541,
      likes: 0,
      contributor_id: 0,
      published_at: '2021-11-10T06:44:20.193Z',
      playback_id: 'ppCBXN7CGvl5S01SpnvDDgfBRJMhRYwZ1',
      aspect_ratio: '16:9',
      duration: 18.601922,
      max_height: 1152,
      max_width: 2048,
      video_id: '6bf85cf0-28c5-4e50-84b6-d34f2f37dff1',
      id: 'fvWfCdP2vc',
      published_at_timestamp: 1636526660193,
      d2v_ratio: 0,
      objectID: 'fvWfCdP2vc',
    },
    {
      title: 'Asian man getting a jacket out of his car',
      description:
        'Medium close-up shot of an Asian man getting a jacket out of his car.\n',
      tags: [
        'gets out',
        'jacket',
        'car',
        'city',
        'street',
        'night',
        'man',
        'guy',
        'asian',
        'outerwear',
        'bokeh',
        'street light',
        'city life',
        'night life',
        'night light',
        'high-rise building',
        'skyline',
        'cityscape',
        'urban',
        'people',
        'lifestyle',
      ],
      downloads: 27309,
      is_vertical: false,
      created_at: '2021-10-26T09:22:46.953Z',
      updated_at: '2021-12-01T20:00:43.531Z',
      base_filename: 'coverr--08-21-asian-man-night-street_19-0098',
      poster: 'https://storage.coverr.co/p/6UYMtqlSEUt7hYZZlvvgekfWqSwVOka7',
      thumbnail: 'https://storage.coverr.co/t/6UYMtqlSEUt7hYZZlvvgekfWqSwVOka7',
      state: 'published',
      views: 2298,
      likes: 0,
      contributor_id: 0,
      published_at: '2021-11-10T06:44:18.047Z',
      playback_id: '6UYMtqlSEUt7hYZZlvvgekfWqSwVOka7',
      aspect_ratio: '16:9',
      duration: 15.849167,
      max_height: 1152,
      max_width: 2048,
      video_id: '3686de8e-1cea-4e1f-87a8-f3beaf13bbbb',
      id: 'zGLuNAmLvv',
      published_at_timestamp: 1636526658047,
      d2v_ratio: 0,
      objectID: 'zGLuNAmLvv',
    },
    {
      title: 'Asian guy putting his glasses on',
      description:
        'Medium close-up shot of an Asian guy putting his glasses on at night.\n',
      tags: [
        'putting on',
        'glasses',
        'night',
        'street',
        'city',
        'guy',
        'asian',
        'bokeh',
        'cityscape',
        'night life',
        'night light',
        'city life',
        'street light',
        'serious',
        'stylish',
        'man',
        'walking',
        'skyline',
        'evening',
        'urban',
        'people',
        'lifestyle',
      ],
      downloads: 27009,
      is_vertical: false,
      created_at: '2021-10-25T13:50:44.311Z',
      updated_at: '2021-12-01T20:00:43.531Z',
      base_filename: 'coverr--08-21-asian-man-night-street_10-1915',
      poster: 'https://storage.coverr.co/p/FkUHzWJapgxe2HZDzjPwISP1xj0277moj',
      thumbnail:
        'https://storage.coverr.co/t/FkUHzWJapgxe2HZDzjPwISP1xj0277moj',
      state: 'published',
      views: 1557,
      likes: 0,
      contributor_id: 0,
      published_at: '2021-11-10T06:44:08.000Z',
      playback_id: 'FkUHzWJapgxe2HZDzjPwISP1xj0277moj',
      aspect_ratio: '16:9',
      duration: 13.930589,
      max_height: 1152,
      max_width: 2048,
      video_id: '921d3644-c219-4baa-a291-0d70375b83dd',
      id: 'brgD374JNL',
      published_at_timestamp: 1636526648000,
      d2v_ratio: 0,
      objectID: 'brgD374JNL',
    },
    {
      created_at: '2018-07-09T22:49:05.633Z',
      updated_at: '2021-12-01T20:00:41.270Z',
      title: 'Goats eating grass',
      base_filename: 'Go-Goat',
      poster: 'https://storage.coverr.co/p/BQF01AzNvx701ASArKNWZBdDNyTQ00CyCQS',
      thumbnail:
        'https://storage.coverr.co/t/BQF01AzNvx701ASArKNWZBdDNyTQ00CyCQS',
      description:
        'Black and white shot of a couple of goats eating some grass. ',
      state: 'published',
      is_vertical: false,
      tags: [
        'goat',
        'eating',
        'grass',
        'black and white',
        'animals',
        'flower',
        'happy',
        'close up',
        'country',
        'eat',
        'food',
        'rural',
        'background',
        'cute',
        'adorable',
        'white',
        'barn',
      ],
      downloads: 26021,
      views: 103157,
      likes: 0,
      contributor_id: 0,
      published_at: '2016-04-25T00:00:00.000Z',
      playback_id: 'BQF01AzNvx701ASArKNWZBdDNyTQ00CyCQS',
      aspect_ratio: '16:9',
      duration: 15.02,
      max_height: 1080,
      max_width: 1920,
      video_id: '68b85227-b1b7-43c3-a335-df59b0d7a6a6',
      d2v_ratio: 0.4028888,
      id: 'vYqPUwRS8m',
      published_at_timestamp: 1461542400000,
      objectID: 'vYqPUwRS8m',
    },
    {
      title: 'Male photographer in a jungle',
      description: 'Medium close-up shot of a male photographer in a jungle. ',
      tags: [
        'photographer',
        'jungle',
        'camera',
        'man',
        'guy',
        'digital',
        'take a photo',
        'make photo',
        'palm trees',
        'vegetation',
        'green',
        'greenery',
        'focus',
        'lens',
        'photographing',
        'pictures',
        'photos',
        'shooting',
        'people',
        'artsy',
      ],
      downloads: 25494,
      is_vertical: false,
      created_at: '2021-05-24T12:12:35.034Z',
      updated_at: '2021-12-01T20:00:39.793Z',
      base_filename: 'coverr-male-photographer-in-the-jungke-6166',
      poster: 'https://storage.coverr.co/p/B01MQhpdvb00EeS3lxkHVGr9zI6yYeJsMQ',
      thumbnail:
        'https://storage.coverr.co/t/B01MQhpdvb00EeS3lxkHVGr9zI6yYeJsMQ',
      state: 'published',
      views: 535,
      likes: 0,
      contributor_id: 0,
      published_at: '2021-09-13T06:34:58.086Z',
      playback_id: 'B01MQhpdvb00EeS3lxkHVGr9zI6yYeJsMQ',
      aspect_ratio: '256:135',
      duration: 12.4708,
      max_height: 1080,
      max_width: 2048,
      video_id: '255e9edf-979f-47db-b55f-b1f7a7518ac7',
      id: 'GgBJKLCgyu',
      published_at_timestamp: 1631514898086,
      d2v_ratio: 0,
      objectID: 'GgBJKLCgyu',
    },
  ]);

  useEffect(() => {
    // fetchAllVideos().then((data) => {
    //   // hits are an array of objects
    //   console.log(data.hits);
    // });
  });

  return (
    <div className="videos_compo">
      {videos.map((video) => (
        <Video key={video.video_id} video={video} />
      ))}
    </div>
  );
}

export default Videos;
